CREATE OR REPLACE VIEW {esquema}.nn_simo_unico AS
SELECT DISTINCT empleo_id,
identificador,
asignacion_salarial,
vigencia_salarial,
concurso_ascenso,
grado_nivel_id,
nivelid,
nivel,
grado,
denominacion,
conv_id,
conv_nombre,
conv_agno,
conv_estado,
conv_padre_id,
conv_padre,
entidad,
nit,
tipo_entidad,
reqs_estudio,
nbc_tecnico,
nbc_esp_tecnico,
nbc_tecnologico,
nbc_esp_tecnologico,
nbc_profesional,
nbc_esp_profesional,
nbc_maestria,
nbc_doctorado,
vacantes_opec,
vacantes_municipios,
inscritos,
aprobo_vrm,
aprobo_escritas,
criterio_id, 
experiencia, 
exp_profesional, 
exp_prof_relacionada, 
exp_laboral, 
exp_labo_relacionada, 
exp_relacionada, 
etiqueta,
sin_experiencia,
agno,
smmlv
FROM nn_simo;

-- Permissions
ALTER TABLE {esquema}.nn_simo_unico OWNER TO usrcosteo;
GRANT ALL ON TABLE {esquema}.nn_simo_unico TO usrcosteo;